commitFormat: angular
title: "Heartbeat release"
branch:
  master: release
changelog:
  docker: 
    latest: true
    repository: "wiedmannfelix/heartbeat"
  printAll: false
  template: ''
  templatePath: ''
release: 'github'
assets:
  - name: ./heartbeat
    compress: false
github:
  repo: "heartbeat"
  user: "fwiedmann"