---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbeat-deployment
  namespace: heartbeat
spec:
  selector:
    matchLabels:
      app: heartbeat
  replicas: 1
  template:
    metadata:
      labels:
        app: heartbeat
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "9001"
    spec:
      containers:
      - name: heartbeat
        image: wiedmannfelix/heartbeat:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - name: heartbeat
          containerPort: 8080
        - name: metrics
          containerPort: 9100
        volumeMounts:
          - name: heartbeat-config
            mountPath: /code/config.yaml
            subPath: config.yaml

      volumes:
          - name: heartbeat-config
            configMap:
              name: heartbeat-config
              items:
              - key: config.yaml
                path: config.yaml


---
apiVersion: v1
kind: Service
metadata:
  name: heartbeat-service
  namespace: heartbeat
spec:
  type: ClusterIP
  selector:
    app: heartbeat
  ports:
  - name: heartbeat
    port: 80
    targetPort: 8080
  - name: metrics
    port: 9100
    targetPort: 9100
